# Generated by Django 3.2.6 on 2021-09-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(default='', max_length=200),
        ),
    ]
