# Generated by Django 3.2.6 on 2021-09-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20210921_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ManyToManyField(related_name='semester', to='course.Semester'),
        ),
    ]
