# Generated by Django 3.2.6 on 2021-09-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20210926_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ManyToManyField(related_name='semester', to='course.Semester'),
        ),
    ]
