# Generated by Django 3.2.6 on 2021-09-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('title', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=10)),
                ('htmldata', models.CharField(max_length=1000)),
            ],
        ),
    ]
