# Generated by Django 3.2.6 on 2022-01-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=10)),
                ('column_type', models.CharField(blank=True, max_length=20)),
                ('content', models.CharField(blank=True, max_length=100)),
                ('pic', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
