# Generated by Django 3.2.6 on 2021-09-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AI_challenge',
            fields=[
                ('title', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('assign', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=50)),
                ('award', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('assign', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
    ]
