# Generated by Django 3.2.6 on 2021-09-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_challenge',
            name='area',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ai_challenge',
            name='assign',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ai_challenge',
            name='award',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ai_challenge',
            name='date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ai_challenge',
            name='label',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ai_challenge',
            name='link',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ai_challenge',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
