# Generated by Django 3.2.6 on 2021-10-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_challenge',
            name='area',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ai_challenge',
            name='award',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
