# Generated by Django 3.2.6 on 2021-10-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seminal',
            new_name='Seminar',
        ),
    ]
