# Generated by Django 3.2.6 on 2022-01-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0002_rename_seminal_seminar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminar',
            old_name='source',
            new_name='slide',
        ),
    ]
