# Generated by Django 3.2.6 on 2022-01-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0003_rename_source_seminar_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='source',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
