# Generated by Django 3.2.6 on 2021-10-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('link', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Research_interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Graduated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10)),
                ('course', models.CharField(blank=True, max_length=30)),
                ('admission_date', models.CharField(blank=True, max_length=10)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('pic', models.CharField(blank=True, max_length=20)),
                ('linked', models.ManyToManyField(related_name='linked', to='member.Linked')),
                ('research_interests', models.ManyToManyField(related_name='research_interests', to='member.Research_interests')),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10)),
                ('course', models.CharField(blank=True, max_length=30)),
                ('graduate_year', models.CharField(max_length=10, null=True)),
                ('team', models.ManyToManyField(related_name='team', to='member.Team')),
            ],
        ),
    ]
