# Generated by Django 3.2.6 on 2022-01-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='alumni', to='member.Project'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='team',
            field=models.ManyToManyField(related_name='alumni', to='member.Team'),
        ),
        migrations.AlterField(
            model_name='graduated',
            name='linked',
            field=models.ManyToManyField(blank=True, related_name='graduated', to='member.Linked'),
        ),
        migrations.AlterField(
            model_name='graduated',
            name='research_interests',
            field=models.ManyToManyField(blank=True, related_name='graduated', to='member.Research_interests'),
        ),
    ]
