# Generated by Django 3.2.6 on 2021-10-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20211004_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduated',
            name='linked',
            field=models.ManyToManyField(blank=True, related_name='linked', to='member.Linked'),
        ),
        migrations.AlterField(
            model_name='graduated',
            name='research_interests',
            field=models.ManyToManyField(blank=True, related_name='research_interests', to='member.Research_interests'),
        ),
    ]
