# Generated by Django 3.2.6 on 2022-01-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20220116_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
