# Generated by Django 3.2.6 on 2021-10-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20211012_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduated',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
