# Generated by Django 3.2.6 on 2022-01-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='course',
        ),
    ]
