# Generated by Django 3.2.6 on 2022-01-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20220112_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='project', to='member.Project'),
        ),
    ]
