# Generated by Django 3.2.6 on 2022-01-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_remove_master_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dissertation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('paper_link', models.CharField(blank=True, max_length=50)),
                ('slide_link', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='master',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='master',
            name='research_interests',
        ),
        migrations.AddField(
            model_name='master',
            name='dissertation',
            field=models.ManyToManyField(blank=True, related_name='master', to='member.Dissertation'),
        ),
    ]
