# Generated by Django 3.2.6 on 2022-01-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20220128_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertation',
            name='paper_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='slide_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
